site_name: allink-core-static
pages:
  - Overview:
    - Introduction: 'index.md'
    - Important notes: 'important.md'
    - How to update: 'update.md'
    - Webpack: 'webpack.md'
    - NPM: 'npm.md'
  - Javascript:
    - General Usage: 'javascript/usage.md'
    - Custom Events: 'javascript/custom-events.md'
    - Libraries: 'javascript/libraries.md'
  - Stylesheets:
    - Concept: 'stylesheets/concept.md'
    - Libraries: 'stylesheets/libraries.md'
    - Usage: 'stylesheets/usage.md'
  - Templates:
    - Base: 'html/base.md'
    - Setting up page templates: 'html/page-templates.md'
    - Plugin template: 'html/plugins.md'
  extra_css:
      - custom.css

markdown_extensions:
    - admonition

theme: readthedocs
