site_name: allink-core-static
pages:
  - Introduction: 'index.md'
  - Overview:
    - Important notes: 'important.md'
    - How to update: 'update.md'
    - Webpack: 'webpack.md'
    - NPM: 'npm.md'
  - Javascript:
    - General Usage: 'javascript/usage.md'
    - Custom Events: 'javascript/custom-events.md'
    - Libraries: 'javascript/libraries.md'
  - Stylesheets:
    - General Usage: 'stylesheets/usage.md'
    - Libraries: 'stylesheets/libraries.md'
    - Styleguide: 'stylesheets/styleguide.md'
    - Variables: 'stylesheets/variables.md'
    - Grid: 'stylesheets/grid.md'
    - Colors: 'stylesheets/colors.md'
  - Templates:
    - Base: 'html/base.md'
    - Setting up page templates: 'html/page-templates.md'
    - Setting up app plugin templates: 'html/plugins.md'

extra_css:
    - custom.css

markdown_extensions:
    - admonition

theme: readthedocs
